//! Production ↔ formal decision-contract refinement oracle for the
//! episode terminal settlement evidence
//! (specs/episode-terminal-settlement). Verifier-only: this test adds
//! no production vocabulary and defines no semantics — it freezes what
//! the CURRENT production resolver does so that production and the TLA
//! decision functions (`CurrentDecisionDecisive` /
//! `CurrentDecisionVerdict`) cannot drift apart silently.
//!
//! What it freezes: for every evidence tuple
//!   (stop_intent, decode_failure, worker_terminal, drain_verdict)
//! over the full finite domain (2 × 2 × 4 × 3 = 48 rows) — driven
//! through the real public `SessionCompletion` seam, one fresh handle
//! per tuple, resolved exactly once — the table records the outcome
//! class:
//!   undecided | completed | stopped | failed-decode | failed-device
//! (the failed-decode / failed-device split preserves production's
//! `Failed.stage` naming; the TLA verdict collapses both to "Failed").
//!
//! The committed artifact
//!   specs/episode-terminal-settlement/CurrentDecisionTable.tla
//! is generated BY this test and read by the TLC refinement run
//! (`EpisodeTerminalSettlementTable`), which checks the table row by
//! row against the formal decision functions. Two gates, one artifact:
//!   - this test (Verification Rust Gate) pins production ⇒ table;
//!   - the TLC run (Formal Semantic Gate) pins table ⇒ formal defs.
//! Any change to `completion.rs::resolve`'s decision contract therefore
//! fails CI until the artifact is regenerated AND the formal decision
//! functions still agree with the regenerated table.
//!
//! Regenerate only after an authority-recorded decision-contract
//! change (ADR-PBK-002 §17 D11):
//!   QIANQIAN_UPDATE_DECISION_TABLE=1 \
//!     cargo test -p qianqian-playback --test completion_decision_table
//! then re-run `specs/check.sh terminal` — the TLC refinement run must
//! still pass before the change can merge.
//!
//! Scope boundary (known differential, deliberately NOT in this
//! table's domain): the table freezes the STATIC decision contract
//! (evidence shape ⇒ verdict class, intent fixed at resolve time).
//! The dynamic differential — production `resolve()` reads the current
//! stop intent while the model freezes boundary intent — is recorded
//! by D11, machine-checked on the formal side (M4/W4), and is the F2
//! correction target.

use std::fmt::Write as _;

use qianqian_playback::{DrainVerdict, EdgeTerminal, SessionCompletion, SessionOutcome};

const TABLE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../specs/episode-terminal-settlement/CurrentDecisionTable.tla"
);

/// Canonical domain order. The row order of the generated table is the
/// nesting order of these arrays (stop_intent outermost, drain_verdict
/// innermost) and must stay stable: the committed artifact is compared
/// byte for byte (modulo line endings).
const STOP_INTENTS: [bool; 2] = [false, true];
const DECODE_FAILURES: [bool; 2] = [false, true];
/// `EdgeTerminal::Open` is not a worker-exit value: the exit seam
/// (`session.rs::decode_worker`) reaches `worker_exited` only after
/// close_eof / fail / stop, so the modeled domain is exactly
/// None | Eof | Stopped | Failed.
const WORKER_TERMINALS: [(&str, Option<EdgeTerminal>); 4] = [
    ("None", None),
    ("Eof", Some(EdgeTerminal::Eof)),
    ("Stopped", Some(EdgeTerminal::Stopped)),
    ("Failed", Some(EdgeTerminal::Failed)),
];
const DRAIN_VERDICTS: [(&str, Option<DrainVerdict>); 3] = [
    ("None", None),
    ("Drained", Some(DrainVerdict::Drained)),
    ("Aborted", Some(DrainVerdict::Aborted)),
];

/// The frozen class vocabulary. `Failed.stage` naming is realization
/// detail: a stage outside the two frozen names fails the test rather
/// than being silently absorbed.
const CLASSES: [&str; 5] = [
    "undecided",
    "completed",
    "stopped",
    "failed-decode",
    "failed-device",
];

fn classify(outcome: Option<SessionOutcome>) -> &'static str {
    match outcome {
        None => "undecided",
        Some(SessionOutcome::Completed) => "completed",
        Some(SessionOutcome::Stopped) => "stopped",
        Some(SessionOutcome::Failed { stage }) if stage.starts_with("decode") => "failed-decode",
        Some(SessionOutcome::Failed { stage }) if stage == "device" => "failed-device",
        Some(SessionOutcome::Failed { stage }) => {
            panic!("unfrozen failure stage in decision table: {stage:?}")
        }
    }
}

/// Drive one fresh `SessionCompletion` through the public seam exactly
/// as the session legs drive it, then resolve once. Publication order
/// is irrelevant on a fresh handle: every publisher here is a write-once
/// state recorder and no edge is ever bound (so `request_stop` only
/// records intent).
fn production_class(
    stop_intent: bool,
    decode_failure: bool,
    worker_terminal: Option<EdgeTerminal>,
    drain_verdict: Option<DrainVerdict>,
) -> &'static str {
    let completion = SessionCompletion::new();
    if decode_failure {
        completion.decode_failed("oracle probe");
    }
    if let Some(terminal) = worker_terminal {
        completion.worker_exited(terminal);
    }
    if let Some(verdict) = drain_verdict {
        completion.drain_signal().complete(verdict);
    }
    if stop_intent {
        completion.request_stop();
    }
    classify(completion.try_resolve_now())
}

fn tla_bool(value: bool) -> &'static str {
    if value { "TRUE" } else { "FALSE" }
}

const ARTIFACT_HEADER: &str = concat!(
    "--------------------------- MODULE CurrentDecisionTable ---------------------------\n",
    "(**************************************************************************)\n",
    "(* 生成文件 —— 请勿手改。                                                 *)\n",
    "(*                                                                        *)\n",
    "(* episode terminal settlement 的 production ↔ formal 判决合同            *)\n",
    "(* refinement oracle 共享真值表（CORRECTIVE-2）：对证据元组               *)\n",
    "(*   <<stop_intent, decode_failure, worker_terminal, drain_verdict,       *)\n",
    "(*     class>>                                                             *)\n",
    "(* 在完整有限域（2 × 2 × 4 × 3 = 48 行）上穷举冻结**当前** production      *)\n",
    "(* 判决器（qianqian-playback SessionCompletion::resolve，经公开 seam      *)\n",
    "(* 逐元组驱动）的 decisive 域与判决类。                                   *)\n",
    "(*                                                                        *)\n",
    "(* 生成/比对：crates/qianqian-playback/tests/                              *)\n",
    "(* completion_decision_table.rs（Verification Rust Gate 执行）。          *)\n",
    "(* 消费：EpisodeTerminalSettlementTable.tla 的 TLC run（Formal Semantic   *)\n",
    "(* Gate 执行）逐行校验本表与 CurrentDecisionDecisive /                    *)\n",
    "(* CurrentDecisionVerdict 一致。两侧共用这一个 artifact：改               *)\n",
    "(* completion.rs 判决合同、手改本表、或改 TLA 判决函数，任何漂移都会击穿   *)\n",
    "(* 对应 gate。                                                             *)\n",
    "(*                                                                        *)\n",
    "(* 再生成（仅限 authority 记录在案的判决合同变更，ADR-PBK-002 §17 D11）：  *)\n",
    "(*   QIANQIAN_UPDATE_DECISION_TABLE=1 cargo test -p qianqian-playback \\   *)\n",
    "(*     --test completion_decision_table                                   *)\n",
    "(* 之后必须重跑 specs/check.sh terminal（TLC refinement run 必须仍 PASS）。*)\n",
    "(*                                                                        *)\n",
    "(* verifier-only evidence（AGENTS.md verification authority boundary）：   *)\n",
    "(* 本表是 refinement oracle，不是 authority；语义只在 ADR-PBK-001 §2 与    *)\n",
    "(* ADR-PBK-002 §17 D11。表冻结的是**静态**判决合同（证据形状 → 判决类，    *)\n",
    "(* intent 在 resolve 时刻固定）；production resolve() 读当前 stop intent   *)\n",
    "(* 的 known differential（late intent）不在此表域内——由主模型 M4/W4       *)\n",
    "(* 机器检查、D11 记录、F2 修正。                                           *)\n",
    "(**************************************************************************)\n",
);

/// Render the complete artifact text from the live production truth.
fn render_table() -> String {
    let mut rows = Vec::with_capacity(48);
    for stop_intent in STOP_INTENTS {
        for decode_failure in DECODE_FAILURES {
            for (worker_name, worker_terminal) in WORKER_TERMINALS {
                for (drain_name, drain_verdict) in DRAIN_VERDICTS {
                    let class = production_class(
                        stop_intent,
                        decode_failure,
                        worker_terminal,
                        drain_verdict,
                    );
                    let row = format!(
                        "      <<{}, {}, \"{}\", \"{}\", \"{}\">>",
                        tla_bool(stop_intent),
                        tla_bool(decode_failure),
                        worker_name,
                        drain_name,
                        class
                    );
                    rows.push(row);
                }
            }
        }
    }
    let mut out = String::new();
    out.push_str(ARTIFACT_HEADER);
    out.push_str("DecisionTableRows ==\n    {\n");
    out.push_str(&rows.join(",\n"));
    out.push_str("\n    }\n\n");
    let _ = writeln!(
        out,
        "DecisionClasses == {{{}}}",
        CLASSES
            .iter()
            .map(|class| format!("\"{class}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );
    out.push_str("=============================================================================\n");
    out.push_str("\\* #### EOF ####\n");
    out
}

#[test]
fn current_decision_contract_is_frozen_in_the_table_artifact() {
    let expected = render_table();
    let committed = std::fs::read_to_string(TABLE_PATH)
        .map(|text| text.replace("\r\n", "\n"))
        .unwrap_or_default();

    if committed != expected && std::env::var_os("QIANQIAN_UPDATE_DECISION_TABLE").is_some() {
        std::fs::write(TABLE_PATH, &expected)
            .unwrap_or_else(|e| panic!("regenerate {TABLE_PATH}: {e}"));
        println!("regenerated {TABLE_PATH} from the live production resolver");
        return;
    }

    assert_eq!(
        committed, expected,
        concat!(
            "the production decision contract no longer matches the frozen table artifact\n",
            "(or the artifact was hand-edited).\n",
            "If this is an authority-recorded decision-contract change: regenerate with\n",
            "  QIANQIAN_UPDATE_DECISION_TABLE=1 cargo test -p qianqian-playback",
            " --test completion_decision_table\n",
            "then re-run specs/check.sh terminal — the TLC refinement run",
            " (EpisodeTerminalSettlementTable) must still pass so the formal",
            " decision functions are re-validated against the new table."
        )
    );
}
