set_project("qianqian")
set_version("0.1.0")
set_languages("c11")
set_config("builddir", "build/xmake")
add_rules("mode.debug", "mode.release")

-- WASM sessions: every target in the session (including the FFmpeg closure
-- replay in qianqian_av) compiles with the guest toolchain. The native
-- default session stays untouched.
if get_config("wasm") == "wasi" then
    set_toolchains("wasi-sdk")
elseif get_config("wasm") == "emscripten" then
    set_toolchains("emcc")
end

-- Which frozen compile closure qianqian_av replays. Defaults to the
-- canonical import manifest (build/ffmpeg-xmake/manifest.json); test and
-- DSP closures are generated by the profile importer into
-- build/minimize/<profile>/ and pointed at with this option.
option("av_manifest")
    set_default("build/ffmpeg-xmake/manifest.json")
    set_showmenu(true)
    set_description("FFmpeg compile-closure manifest to replay")

-- Product build controls: section GC and link-time optimization for the
-- final artifact size.
option("gc_sections")
    set_default(false)
    set_showmenu(true)
    set_description("Link with -Wl,--gc-sections (section garbage collection)")

option("lto")
    set_default(false)
    set_showmenu(true)
    set_description("Link with -flto (link-time optimization)")

local artifact_dir = path.join(os.projectdir(), "build", "artifacts")
local ffmpeg_manifest = function ()
    return path.join(os.projectdir(), get_config("av_manifest"))
end

-- Import is intentionally separate from normal builds. It may invoke FFmpeg's
-- configure/Make once as an upstream oracle, then freezes the exact compile
-- closure in build/ffmpeg-xmake/manifest.json. Normal xmake builds never call
-- FFmpeg Makefiles.
task("ffmpeg-import")
    set_menu {
        usage = "xmake ffmpeg-import",
        description = "Resolve the minimal FFmpeg source closure for Xmake replay"
    }
    on_run(function ()
        import("lib.detect.find_tool")
        local python = find_tool("python3") or find_tool("python")
        assert(python, "python3/python is required for ffmpeg-import")
        os.execv(python.program, {path.join(os.projectdir(), "tools", "ffmpeg_import.py")})
    end)

target("qianqian_av")
    set_kind("static")
    set_default(false)
    set_targetdir(artifact_dir)
    on_load(function (target)
        import("core.base.json")
        -- Do not fail project loading here: `xmake ffmpeg-import` must be able
        -- to run before the manifest exists. before_build below owns the gate.
        local manifest_path = ffmpeg_manifest()
        if not os.isfile(manifest_path) then
            return
        end

        local m = json.loadfile(manifest_path)
        local srcroot = path.join(os.projectdir(), m.source_root)
        local buildroot = path.join(os.projectdir(), m.config_root)

        -- Generated config headers must win over the pristine source tree.
        target:add("includedirs", buildroot, srcroot, {public = true})

        -- WASM sessions replay the closure at -Os (shipping shape). The
        -- manifest keeps the oracle's own flags untouched; codegen level is
        -- a build decision.
        local optimize_flags = function (flags)
            local out = {}
            for _, flag in ipairs(flags) do
                if flag:match("^%-O") then
                    flag = "-Os"
                end
                table.insert(out, flag)
            end
            return out
        end
        local wasm_session = (get_config("wasm") ~= nil and get_config("wasm") ~= false)

        for _, unit in ipairs(m.units) do
            local root = unit.origin == "generated" and buildroot or srcroot
            local source = path.join(root, unit.path)
            local flags = {}
            for _, flag in ipairs(unit.flags or {}) do
                flag = flag:gsub("@SRC@", function () return srcroot end)
                flag = flag:gsub("@BUILD@", function () return buildroot end)
                table.insert(flags, flag)
            end
            if wasm_session then
                flags = optimize_flags(flags)
            end
            if #flags > 0 then
                local force = {}
                force[unit.flag_kind or "cflags"] = flags
                target:add("files", source, {force = force})
            else
                target:add("files", source)
            end
        end
    end)
    before_build(function ()
        if not os.isfile(ffmpeg_manifest()) then
            raise("FFmpeg source closure is missing. Run `xmake ffmpeg-import` first, then rerun xmake.")
        end
    end)

target("songcore")
    set_kind("static")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("src/songcore_ffmpeg.c")
    add_includedirs("include", {public = true})
    add_deps("qianqian_av")

target("qn_pcm_dump")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tools/qn_pcm_dump.c")
    add_deps("songcore")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    if is_plat("mingw") then
        -- FFmpeg's av_random_bytes uses BCryptGenRandom on Windows
        add_syslinks("bcrypt")
    end
    on_load(function (target)
        if get_config("gc_sections") then
            target:add("ldflags", "-Wl,--gc-sections")
        end
        if get_config("lto") then
            target:add("ldflags", "-flto=auto")
        end
    end)

-- SongCore ABI v1 machine-test instrument (test-only, one JSON per run).
target("songcore_probe")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tests/songcore/songcore_probe.c")
    add_deps("songcore")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    if is_plat("mingw") then
        add_syslinks("bcrypt")
    end
    -- `xmake test`: full SongCore regression + fail-closed --check.
    -- os.execv raises on nonzero exit, so a gate failure fails the test.
    add_tests("default")
    on_test(function (target, opt)
        import("lib.detect.find_tool")
        local python = find_tool("python3") or find_tool("python")
        if not python then
            return false, "python3 is required for the SongCore regression"
        end
        local root = os.projectdir()
        local out = path.join(root, "bench", "results", "songcore-v1")
        local script = path.join(root, "tests", "songcore", "regression.py")
        os.execv(python.program, {script, "--out", out})
        os.execv(python.program, {script, "--check", "--out", out})
        return true
    end)

-- DSP capability probe (test-only): links the FFmpeg closure replayed by
-- qianqian_av and exercises the filters that closure enables — registration
-- presence/absence, negotiated formats, correctness smokes, graph lifecycle.
-- Used by tests/songcore/dsp_src.py and by tools/dsp_closure.py for the
-- capability-driven libavfilter closure ladder.
target("dsp_cap_probe")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tests/songcore/dsp_cap_probe.c")
    add_deps("qianqian_av", "songcore")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    on_load(function (target)
        if get_config("gc_sections") then
            target:add("ldflags", "-Wl,--gc-sections")
        end
        if get_config("lto") then
            target:add("cflags", "-flto")
            target:add("ldflags", "-flto=auto")
        end
        -- A codec-only closure (no libavfilter) has nothing to link: the
        -- probe compiles its fail-closed stub backend instead.
        if os.getenv("QN_PROBE_NO_AVFILTER") then
            target:add("defines", "QN_PROBE_NO_AVFILTER")
        end
    end)

-- ====================================================================
-- WASM target (independent session; the native default session above is
-- untouched).
--
--   WASI session:
--     xmake f -b build/xmake-wasi --wasm=wasi \
--         --av_manifest=build/ffmpeg-xmake-wasi/manifest.json
--     xmake build songcore_wasm
--
--   Emscripten session:
--     xmake f -b build/xmake-em --wasm=emscripten \
--         --av_manifest=build/ffmpeg-xmake-emscripten/manifest.json
--     xmake build songcore_wasm
--
-- WASM viability was verified against machine evidence (see docs/wasm.md
-- and bench/results/wasm-summary.json); native remains the shipping default.
-- ====================================================================

option("wasm")
    set_values(false, "wasi", "emscripten")
    set_default(false)
    set_showmenu(true)
    set_description("WASM target for this build session")

option("wasmsdk")
    set_default("")
    set_showmenu(true)
    set_description("Override wasi-sdk/emscripten SDK root (else QN_WASI_SDK/QN_EMSDK or ~/toolchains/wasm)")

local wasm_sdk_home = function ()
    return path.join(os.getenv("HOME"), "toolchains", "wasm")
end

toolchain("wasi-sdk")
    set_kind("standalone")
    on_load(function (toolchain)
        local sdk = get_config("wasmsdk")
        if not sdk or #sdk == 0 then sdk = os.getenv("QN_WASI_SDK") end
        if not sdk or #sdk == 0 then
            sdk = path.join(wasm_sdk_home(), "wasi-sdk-34.0")
        end
        local bin = path.join(sdk, "bin")
        local sysroot = path.join(sdk, "share", "wasi-sysroot")
        local triple = "--target=wasm32-wasip1"
        toolchain:set("toolset", "cc", path.join(bin, "clang"))
        toolchain:set("toolset", "cxx", path.join(bin, "clang++"))
        toolchain:set("toolset", "ld", path.join(bin, "clang"))
        toolchain:set("toolset", "sh", path.join(bin, "clang"))
        toolchain:set("toolset", "as", path.join(bin, "clang"))
        toolchain:set("toolset", "ar", path.join(bin, "llvm-ar"))
        toolchain:set("toolset", "strip", path.join(bin, "llvm-strip"))
        toolchain:set("toolset", "nm", path.join(bin, "llvm-nm"))
        toolchain:add("cxflags", triple, "--sysroot=" .. sysroot,
                     "-D_WASI_EMULATED_PROCESS_CLOCKS", {force = true})
        toolchain:add("asflags", triple, "--sysroot=" .. sysroot, {force = true})
        toolchain:add("ldflags", triple, "--sysroot=" .. sysroot,
                     "-D_WASI_EMULATED_PROCESS_CLOCKS",
                     "-lwasi-emulated-process-clocks", {force = true})
        toolchain:add("shflags", triple, "--sysroot=" .. sysroot, {force = true})
    end)

toolchain("emcc")
    set_kind("standalone")
    on_load(function (toolchain)
        local sdk = get_config("wasmsdk")
        if not sdk or #sdk == 0 then sdk = os.getenv("QN_EMSDK") end
        if not sdk or #sdk == 0 then
            sdk = path.join(wasm_sdk_home(), "emsdk", "upstream", "emscripten")
        end
        toolchain:set("toolset", "cc", path.join(sdk, "emcc"))
        toolchain:set("toolset", "cxx", path.join(sdk, "em++"))
        toolchain:set("toolset", "ld", path.join(sdk, "emcc"))
        toolchain:set("toolset", "sh", path.join(sdk, "emcc"))
        toolchain:set("toolset", "ar", path.join(sdk, "emar"))
        toolchain:set("toolset", "ranlib", path.join(sdk, "emranlib"))
        toolchain:set("toolset", "strip", path.join(sdk, "emstrip"))
    end)

-- WASM guest artifacts live in their own artifact subdir.
local wasm_artifact_dir = path.join(artifact_dir, "wasm")

-- Reactor link shape shared by every WASI guest module: no _start, callers
-- initialize via _initialize, linear memory exported for host-side PCM reads.
-- Pin explicit memory bounds (LLVM 23 derives starved ceilings for reactor
-- modules, which starves FFmpeg allocation); actual usage is measured.
-- Exporting __heap_base is REQUIRED for WAMR embedding — without it WAMR
-- places its app heap at __data_end and stomps guest .bss.
local wasi_reactor_ldflags = function ()
    return {
        "-mexec-model=reactor",
        "-Wl,--export-memory",
        "-Wl,--export-if-defined=__heap_base",
        "-Wl,-z,stack-size=1048576",
        "-Wl,--initial-memory=16777216",
        "-Wl,--max-memory=268435456",
    }
end

if get_config("wasm") then
    target("songcore_wasm_lib")
        set_kind("static")
        set_default(false)
        set_targetdir(wasm_artifact_dir)
        set_optimize("smallest")
        add_files("src/songcore_ffmpeg.c")
        add_includedirs("include", {public = true})
        add_deps("qianqian_av")

    target("songcore_wasm")
        set_kind("binary")
        set_default(false)
        set_targetdir(wasm_artifact_dir)
        set_basename("SongCore")
        set_extension(".wasm")
        if get_config("wasm") == "emscripten" then
            set_extension(".js") -- MODULARIZE glue + .wasm side by side
        end
        set_optimize("smallest")
        add_files("src/songcore_ffmpeg.c", "src/wasm/songcore_wasm_bridge.c")
        add_includedirs("include", "src/wasm")
        add_deps("qianqian_av")
        if get_config("wasm") == "wasi" then
            add_ldflags(wasi_reactor_ldflags(), {force = true})
        else
            -- Emscripten: keep the same exports addressable from JS glue.
            add_ldflags({
                "--no-entry", -- library-style module: init via emscripten runtime
                "-sERROR_ON_UNDEFINED_SYMBOLS=0", -- host imports come from the embedder
                "-sALLOW_MEMORY_GROWTH=1",
                "-sMODULARIZE=1",
                "-sEXPORT_NAME=createSongCore",
                "-sINVOKE_RUN=0",
                "-sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPF32",
                "-sEXPORTED_FUNCTIONS=[\"_song_wasm_abi_version\",\"_song_wasm_open\",\"_song_wasm_probe\",\"_song_wasm_audio_stream_count\",\"_song_wasm_audio_stream_info\",\"_song_wasm_select_stream\",\"_song_wasm_get_metadata\",\"_song_wasm_get_metadata_count\",\"_song_wasm_get_metadata_entry\",\"_song_wasm_get_artwork_count\",\"_song_wasm_get_artwork_item\",\"_song_wasm_read_pcm\",\"_song_wasm_seek\",\"_song_wasm_last_error\",\"_song_wasm_close\",\"_malloc\",\"_free\"]",
                "-g1", -- keep export symbol names for the JS glue
                "-sENVIRONMENT=node,web",
            }, {force = true})
        end
end
