set_project("qianqian")
set_version("0.1.0")
set_languages("c11")
set_config("builddir", "build/xmake")
add_rules("mode.debug", "mode.release")

-- WASM sessions: every target in the session (including the FFmpeg closure
-- replay in qianqian_av) compiles with the guest toolchain. The native
-- default session stays untouched.
if get_config("wasm") == "wasi" then
    set_toolchains("wasi-sdk")
elseif get_config("wasm") == "emscripten" then
    set_toolchains("emcc")
end

-- Which frozen compile closure qianqian_av replays. Defaults to the
-- canonical import manifest (build/ffmpeg-xmake/manifest.json); test and
-- DSP closures are generated by the profile importer into
-- build/minimize/<profile>/ and pointed at with this option.
option("av_manifest")
    set_default("build/ffmpeg-xmake/manifest.json")
    set_showmenu(true)
    set_description("FFmpeg compile-closure manifest to replay")

-- Product build controls: section GC and link-time optimization for the
-- final artifact size.
option("gc_sections")
    set_default(false)
    set_showmenu(true)
    set_description("Link with -Wl,--gc-sections (section garbage collection)")

option("lto")
    set_default(false)
    set_showmenu(true)
    set_description("Link with -flto (link-time optimization)")

local artifact_dir = path.join(os.projectdir(), "build", "artifacts")
-- WASM sessions archive their guest closure here as well; sharing the
-- native artifact path would let a wasm-format libsongcore.a silently
-- overwrite the native archive (and vice versa) across sessions.
local wasm_artifact_dir = path.join(artifact_dir, "wasm")
local ffmpeg_manifest = function ()
    return path.join(os.projectdir(), get_config("av_manifest"))
end

-- Fail-closed target identity (docs/ffmpeg-minimization.md): the replayed
-- manifest must have been derived for THIS session's target. A Linux
-- manifest carries generated config headers and architecture sources that
-- are not portable, so it must never silently satisfy a Windows/WASM
-- session. The expected id comes from ffmpeg/targets/*.json — recipes are
-- the machine-readable target intent, Xmake only matches them.
local expected_target_id = function (target, json)
    local wasm = get_config("wasm")
    if wasm == "wasi" then return "wasm-wasi" end
    if wasm == "emscripten" then return "wasm-emscripten" end
    local found = nil
    local targets_dir = path.join(os.projectdir(), "ffmpeg", "targets")
    for _, recipe_file in ipairs(os.files(path.join(targets_dir, "*.json")) or {}) do
        local r = json.loadfile(recipe_file)
        local plats = (r.xmake or {}).plat or {}
        if type(plats) == "string" then plats = {plats} end
        local plat_ok = false
        for _, p in ipairs(plats) do
            if p == target:plat() then plat_ok = true end
        end
        if plat_ok and (r.xmake or {}).arch == target:arch() then
            found = r.id
            break
        end
    end
    return found
end

-- Returns nil when the manifest identity is acceptable for this session,
-- else a fail-closed error message (raise happens in the callback scope).
-- Binds: target id, platform, arch, and the toolchain-family facts
-- (target_os / cross_prefix) the manifest was derived from — so a MinGW
-- manifest can never satisfy an MSVC session (or vice versa), and a
-- manifest derived from an outdated recipe revision is stale.
local manifest_target_problem = function (manifest_path, target, json)
    local m = json.loadfile(manifest_path)
    local mt = m.target or {}
    if not mt.id then
        return format(
            "%s predates target identity (schema < 2). Re-derive it:\n" ..
            "  native session : xmake ffmpeg-import\n" ..
            "  other targets  : python3 tools/ffmpeg_profile_import.py " ..
            "--target <id> --profile ffmpeg/profiles/<capability>.json",
            get_config("av_manifest"))
    end
    local expect = expected_target_id(target, json)
    if not expect then
        return format(
            "no target recipe in ffmpeg/targets/ matches this session " ..
            "(plat '%s', arch '%s'). Target provenance is fail-closed: a " ..
            "session may only replay a manifest derived for a proven " ..
            "target recipe (e.g. MSVC is not yet derived; MinGW " ..
            "manifests do not satisfy MSVC sessions).",
            target:plat(), target:arch())
    end
    if mt.id ~= expect then
        return format(
            "manifest target mismatch: %s was derived for '%s' but this " ..
            "session builds '%s'. Derive the matching closure and point " ..
            "--av_manifest at it:\n" ..
            "  python3 tools/ffmpeg_profile_import.py --target %s " ..
            "--profile ffmpeg/profiles/<capability>.json",
            get_config("av_manifest"), mt.id, expect, expect)
    end
    local recipe_file = path.join(os.projectdir(), "ffmpeg", "targets",
                                  expect .. ".json")
    local recipe = json.loadfile(recipe_file)
    if not recipe then
        return format("target recipe '%s' is missing from ffmpeg/targets/",
                      expect)
    end
    if mt.platform ~= recipe.platform or mt.arch ~= recipe.arch then
        return format(
            "manifest target identity mismatch: %s records %s/%s but the " ..
            "'%s' recipe says %s/%s. Re-derive the closure:\n" ..
            "  python3 tools/ffmpeg_profile_import.py --target %s " ..
            "--profile ffmpeg/profiles/<capability>.json",
            get_config("av_manifest"), mt.platform or "?", mt.arch or "?",
            expect, recipe.platform, recipe.arch, expect)
    end
    local ff = recipe.ffmpeg or {}
    local rederive = format(
        " Re-derive the closure:\n" ..
        "  python3 tools/ffmpeg_profile_import.py --target %s " ..
        "--profile ffmpeg/profiles/<capability>.json", expect)
    if ff.target_os and mt.target_os ~= ff.target_os then
        return format(
            "manifest is stale or from another toolchain family: %s was " ..
            "derived with target_os '%s' but the '%s' recipe binds '%s'.",
            get_config("av_manifest"), mt.target_os or "?", expect,
            ff.target_os) .. rederive
    end
    if ff.cross_prefix and mt.cross_prefix ~= ff.cross_prefix then
        return format(
            "manifest is stale or from another toolchain family: %s was " ..
            "derived with cross_prefix '%s' but the '%s' recipe binds " ..
            "'%s'.",
            get_config("av_manifest"), mt.cross_prefix or "?", expect,
            ff.cross_prefix) .. rederive
    end
    return nil
end

-- Import is intentionally separate from normal builds. It may invoke FFmpeg's
-- configure/Make once as an upstream oracle, then freezes the exact compile
-- closure in build/ffmpeg-xmake/manifest.json. Normal xmake builds never call
-- FFmpeg Makefiles.
task("ffmpeg-import")
    set_menu {
        usage = "xmake ffmpeg-import",
        description = "Resolve the minimal FFmpeg source closure for Xmake replay"
    }
    on_run(function ()
        import("lib.detect.find_tool")
        local python = find_tool("python3") or find_tool("python")
        assert(python, "python3/python is required for ffmpeg-import")
        os.execv(python.program, {path.join(os.projectdir(), "tools", "ffmpeg_import.py")})
    end)

target("qianqian_av")
    set_kind("static")
    set_default(false)
    set_targetdir(artifact_dir)
    on_load(function (target)
        import("core.base.json")
        -- Do not fail project loading here: `xmake ffmpeg-import` must be able
        -- to run before the manifest exists. before_build below owns the gate.
        local manifest_path = ffmpeg_manifest()
        if not os.isfile(manifest_path) then
            return
        end

        local m = json.loadfile(manifest_path)
        local srcroot = path.join(os.projectdir(), m.source_root)
        local buildroot = path.join(os.projectdir(), m.config_root)

        -- Generated config headers must win over the pristine source tree.
        target:add("includedirs", buildroot, srcroot, {public = true})

        -- WASM sessions replay the closure at -Os (shipping shape). The
        -- manifest keeps the oracle's own flags untouched; codegen level is
        -- a build decision.
        local optimize_flags = function (flags)
            local out = {}
            for _, flag in ipairs(flags) do
                if flag:match("^%-O") then
                    flag = "-Os"
                end
                table.insert(out, flag)
            end
            return out
        end
        local wasm_session = (get_config("wasm") ~= nil and get_config("wasm") ~= false)

        for _, unit in ipairs(m.units) do
            local root = unit.origin == "generated" and buildroot or srcroot
            local source = path.join(root, unit.path)
            local flags = {}
            for _, flag in ipairs(unit.flags or {}) do
                flag = flag:gsub("@SRC@", function () return srcroot end)
                flag = flag:gsub("@BUILD@", function () return buildroot end)
                table.insert(flags, flag)
            end
            if wasm_session then
                flags = optimize_flags(flags)
            end
            if #flags > 0 then
                local force = {}
                force[unit.flag_kind or "cflags"] = flags
                target:add("files", source, {force = force})
            else
                target:add("files", source)
            end
        end
    end)
    before_build(function (target)
        if not os.isfile(ffmpeg_manifest()) then
            raise("FFmpeg source closure is missing. Run `xmake ffmpeg-import` first, then rerun xmake.")
        end
        import("core.base.json")
        local problem = manifest_target_problem(ffmpeg_manifest(), target, json)
        if problem then
            raise(problem)
        end
    end)

-- One conceptual native library (songcore), two artifact kinds. The public
-- ABI is include/songcore.h (ABI v1); the target names below are build
-- internals and never appear in the ABI. Shared build logic lives in
-- songcore_common() — the Xmake-recommended way to avoid duplicating the
-- definition across static/shared targets.
local songcore_common = function (dep_av)
    add_files("src/songcore_ffmpeg.c")
    add_includedirs("include", {public = true})
    if dep_av then
        add_deps("qianqian_av")
    end
    if is_plat("linux", "macosx", "android", "iphoneos") then
        add_syslinks("m", "pthread")
    end
    if is_plat("mingw", "windows") then
        -- FFmpeg's av_random_bytes uses BCryptGenRandom on Windows
        add_syslinks("bcrypt")
    end
end

target("songcore_static")
    set_kind("static")
    set_basename("songcore") -- → libsongcore.a / songcore.lib
    set_default(false)
    set_targetdir(get_config("wasm") and wasm_artifact_dir or artifact_dir)
    -- One self-contained static consumer artifact: the FFmpeg closure
    -- (qianqian_av) is merged into libsongcore.a by Xmake's supported
    -- merge policy (ar / lib.exe, cross-toolchain safe), so external
    -- static consumers link exactly one Qianqian archive plus system
    -- libraries — no separate internal archive in the documented link
    -- line. Linkers still drop unreferenced FFmpeg members from the
    -- merged archive member-wise, so test binaries keep their size.
    set_policy("build.merge_archive", true)
    songcore_common(true)

target("songcore_shared")
    set_kind("shared")
    set_basename("songcore") -- → libsongcore.so / songcore.dll
    set_default(false)
    -- Own subdir: a co-located libsongcore.so would win the linker's -l
    -- search over the static archive and silently flip every test binary
    -- to a dynamic dependency (same subdir convention as artifacts/wasm/).
    set_targetdir(path.join(artifact_dir, "shared"))
    add_defines("SONGCORE_BUILD_SHARED")
    -- Hide by default; only SONGCORE_API declarations stay exported. The
    -- statically-linked FFmpeg closure is forced local at link time on ELF
    -- (no Mach-O equivalent yet — macos-arm64 recipe notes this).
    set_symbols("hidden")
    if is_plat("linux", "android") then
        add_ldflags("-Wl,--exclude-libs,ALL", {force = true})
    end
    -- The shared artifact links the SAME merged archive the static
    -- consumers get. Depending on qianqian_av directly is wrong under
    -- build.merge_archive: xmake then treats the closure as "merged into
    -- songcore_static" and drops it from this target's link line, which
    -- ELF silently accepts as undefined references (hollow artifact) and
    -- PE rejects at DLL link time.
    songcore_common(false)
    add_deps("songcore_static")

-- Build convenience: both artifact kinds under the historical name.
target("songcore")
    set_kind("phony")
    set_default(false)
    add_deps("songcore_static", "songcore_shared")

target("qn_pcm_dump")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tools/qn_pcm_dump.c")
    add_deps("songcore_static")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    if is_plat("mingw") then
        -- FFmpeg's av_random_bytes uses BCryptGenRandom on Windows
        add_syslinks("bcrypt")
    end
    on_load(function (target)
        if get_config("gc_sections") then
            target:add("ldflags", "-Wl,--gc-sections")
        end
        if get_config("lto") then
            target:add("ldflags", "-flto=auto")
        end
    end)

-- SongCore ABI v1 machine-test instrument (test-only, one JSON per run).
target("songcore_probe")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tests/songcore/songcore_probe.c")
    add_deps("songcore_static")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    if is_plat("mingw") then
        add_syslinks("bcrypt")
    end
    -- `xmake test`: full SongCore regression + fail-closed --check, then
    -- the external-consumer gates (shared export audit, ctypes decode
    -- consumer, static archive consumer). os.execv raises on nonzero
    -- exit, so a gate failure fails the test.
    add_tests("default")
    on_test(function (target, opt)
        import("lib.detect.find_tool")
        local python = find_tool("python3") or find_tool("python")
        if not python then
            return false, "python3 is required for the SongCore regression"
        end
        local root = os.projectdir()
        local out = path.join(root, "bench", "results", "songcore-v1")
        local script = path.join(root, "tests", "songcore", "regression.py")
        local consumers = path.join(root, "tests", "songcore", "consumers.py")
        os.execv(python.program, {script, "--out", out})
        os.execv(python.program, {script, "--check", "--out", out})
        os.execv(python.program, {consumers, "--out", "--core"})
        os.execv(python.program, {consumers, "--check", "--core"})
        return true
    end)

-- DSP capability probe (test-only): links the FFmpeg closure replayed by
-- qianqian_av and exercises the filters that closure enables — registration
-- presence/absence, negotiated formats, correctness smokes, graph lifecycle.
-- Used by tests/songcore/dsp_src.py and by tools/dsp_closure.py for the
-- capability-driven libavfilter closure ladder.
target("dsp_cap_probe")
    set_kind("binary")
    set_default(false)
    set_targetdir(artifact_dir)
    add_files("tests/songcore/dsp_cap_probe.c")
    -- build.merge_archive: the closure (qianqian_av) lives inside the merged
    -- songcore archive; depending on qianqian_av directly would be silently
    -- dropped from the link line.
    add_deps("songcore_static")
    if is_plat("linux") or is_plat("macosx") then
        add_syslinks("m", "pthread")
    end
    on_load(function (target)
        if get_config("gc_sections") then
            target:add("ldflags", "-Wl,--gc-sections")
        end
        if get_config("lto") then
            target:add("cflags", "-flto")
            target:add("ldflags", "-flto=auto")
        end
        -- A codec-only closure (no libavfilter) has nothing to link: the
        -- probe compiles its fail-closed stub backend instead.
        if os.getenv("QN_PROBE_NO_AVFILTER") then
            target:add("defines", "QN_PROBE_NO_AVFILTER")
        end
    end)

-- ====================================================================
-- WASM target (independent session; the native default session above is
-- untouched).
--
--   WASI session:
--     xmake f -b build/xmake-wasi --wasm=wasi \
--         --av_manifest=build/ffmpeg-xmake-wasi/manifest.json
--     xmake build songcore_wasm
--
--   Emscripten session:
--     xmake f -b build/xmake-em --wasm=emscripten \
--         --av_manifest=build/ffmpeg-xmake-emscripten/manifest.json
--     xmake build songcore_wasm
--
-- WASM viability was verified against machine evidence (see docs/wasm.md
-- and bench/results/wasm-summary.json); native remains the shipping default.
-- ====================================================================

option("wasm")
    set_values(false, "wasi", "emscripten")
    set_default(false)
    set_showmenu(true)
    set_description("WASM target for this build session")

option("wasmsdk")
    set_default("")
    set_showmenu(true)
    set_description("Override wasi-sdk/emscripten SDK root (else QN_WASI_SDK/QN_EMSDK or ~/toolchains/wasm)")

local wasm_sdk_home = function ()
    return path.join(os.getenv("HOME"), "toolchains", "wasm")
end

toolchain("wasi-sdk")
    set_kind("standalone")
    on_load(function (toolchain)
        local sdk = get_config("wasmsdk")
        if not sdk or #sdk == 0 then sdk = os.getenv("QN_WASI_SDK") end
        if not sdk or #sdk == 0 then
            sdk = path.join(wasm_sdk_home(), "wasi-sdk-34.0")
        end
        local bin = path.join(sdk, "bin")
        local sysroot = path.join(sdk, "share", "wasi-sysroot")
        local triple = "--target=wasm32-wasip1"
        toolchain:set("toolset", "cc", path.join(bin, "clang"))
        toolchain:set("toolset", "cxx", path.join(bin, "clang++"))
        toolchain:set("toolset", "ld", path.join(bin, "clang"))
        toolchain:set("toolset", "sh", path.join(bin, "clang"))
        toolchain:set("toolset", "as", path.join(bin, "clang"))
        toolchain:set("toolset", "ar", path.join(bin, "llvm-ar"))
        toolchain:set("toolset", "strip", path.join(bin, "llvm-strip"))
        toolchain:set("toolset", "nm", path.join(bin, "llvm-nm"))
        toolchain:add("cxflags", triple, "--sysroot=" .. sysroot,
                     "-D_WASI_EMULATED_PROCESS_CLOCKS", {force = true})
        toolchain:add("asflags", triple, "--sysroot=" .. sysroot, {force = true})
        toolchain:add("ldflags", triple, "--sysroot=" .. sysroot,
                     "-D_WASI_EMULATED_PROCESS_CLOCKS",
                     "-lwasi-emulated-process-clocks", {force = true})
        toolchain:add("shflags", triple, "--sysroot=" .. sysroot, {force = true})
    end)

toolchain("emcc")
    set_kind("standalone")
    on_load(function (toolchain)
        local sdk = get_config("wasmsdk")
        if not sdk or #sdk == 0 then sdk = os.getenv("QN_EMSDK") end
        if not sdk or #sdk == 0 then
            sdk = path.join(wasm_sdk_home(), "emsdk", "upstream", "emscripten")
        end
        toolchain:set("toolset", "cc", path.join(sdk, "emcc"))
        toolchain:set("toolset", "cxx", path.join(sdk, "em++"))
        toolchain:set("toolset", "ld", path.join(sdk, "emcc"))
        toolchain:set("toolset", "sh", path.join(sdk, "emcc"))
        toolchain:set("toolset", "ar", path.join(sdk, "emar"))
        toolchain:set("toolset", "ranlib", path.join(sdk, "emranlib"))
        toolchain:set("toolset", "strip", path.join(sdk, "emstrip"))
    end)

-- WASM guest artifacts live in their own artifact subdir.

-- Reactor link shape shared by every WASI guest module: no _start, callers
-- initialize via _initialize, linear memory exported for host-side PCM reads.
-- Pin explicit memory bounds (LLVM 23 derives starved ceilings for reactor
-- modules, which starves FFmpeg allocation); actual usage is measured.
-- Exporting __heap_base is REQUIRED for WAMR embedding — without it WAMR
-- places its app heap at __data_end and stomps guest .bss.
local wasi_reactor_ldflags = function ()
    return {
        "-mexec-model=reactor",
        "-Wl,--export-memory",
        "-Wl,--export-if-defined=__heap_base",
        "-Wl,-z,stack-size=1048576",
        "-Wl,--initial-memory=16777216",
        "-Wl,--max-memory=268435456",
    }
end

if get_config("wasm") then
    target("songcore_wasm_lib")
        set_kind("static")
        set_default(false)
        set_targetdir(wasm_artifact_dir)
        set_optimize("smallest")
        add_files("src/songcore_ffmpeg.c")
        add_includedirs("include", {public = true})
        add_deps("songcore_static")

    target("songcore_wasm")
        set_kind("binary")
        set_default(false)
        set_targetdir(wasm_artifact_dir)
        set_basename("SongCore")
        set_extension(".wasm")
        if get_config("wasm") == "emscripten" then
            set_extension(".js") -- MODULARIZE glue + .wasm side by side
        end
        set_optimize("smallest")
        add_files("src/songcore_ffmpeg.c", "src/wasm/songcore_wasm_bridge.c")
        add_includedirs("include", "src/wasm")
        add_deps("songcore_static")
        if get_config("wasm") == "wasi" then
            add_ldflags(wasi_reactor_ldflags(), {force = true})
        else
            -- Emscripten: keep the same exports addressable from JS glue.
            add_ldflags({
                "--no-entry", -- library-style module: init via emscripten runtime
                "-sERROR_ON_UNDEFINED_SYMBOLS=0", -- host imports come from the embedder
                "-sALLOW_MEMORY_GROWTH=1",
                "-sMODULARIZE=1",
                "-sEXPORT_NAME=createSongCore",
                "-sINVOKE_RUN=0",
                "-sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPF32",
                "-sEXPORTED_FUNCTIONS=[\"_song_wasm_abi_version\",\"_song_wasm_open\",\"_song_wasm_probe\",\"_song_wasm_audio_stream_count\",\"_song_wasm_audio_stream_info\",\"_song_wasm_select_stream\",\"_song_wasm_get_metadata\",\"_song_wasm_get_metadata_count\",\"_song_wasm_get_metadata_entry\",\"_song_wasm_get_artwork_count\",\"_song_wasm_get_artwork_item\",\"_song_wasm_read_pcm\",\"_song_wasm_seek\",\"_song_wasm_last_error\",\"_song_wasm_close\",\"_song_wasm_alloc\",\"_song_wasm_free\",\"_song_wasm_layout\",\"_malloc\",\"_free\"]",
                "-g1", -- keep export symbol names for the JS glue
                "-sENVIRONMENT=node,web",
            }, {force = true})
        end
end
