// trace_runner.cpp — deterministic trace replayer for the native engine.
//
// Reads a line-protocol trace (generated by tools/player_model/
// model_equivalence.py from the SAME seeded randomness that drives the
// Python oracle), executes it against the native PlayerEngine + fake
// SongCore, and prints one snapshot line after every operation. The
// generator then compares the two snapshot streams field-by-field.
//
// Harness-level normalizations (player task §45 — normalize at the harness,
// never rewrite the oracle):
//   * remaining hint: the frozen backpressure rule references `remaining`,
//     which the frozen SongCore ABI cannot report. The runner injects the
//     fake's truth before every worker step so the native decision sequence
//     matches the oracle's 1:1 (production derives an estimate instead).
//   * EOF fold: the oracle's chunk.eof flag rides with the final data
//     chunk; the real ABI reports EOF as a separate 0-frame SONG_EOF read.
//     When a decode exhausts the fake, the runner folds that confirmation
//     read into the same trace op so source_eof observably flips at the
//     same op index.
//
// After EVERY operation the runner also re-asserts the native invariants
// (the check_all mirror): ring/decode/output/media conservation, the
// rendered-output split, clock continuity, duration bounds, and per-segment
// content continuity from the fake's hidden frame identities.
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <optional>
#include <string>
#include <vector>

#include "fake_songcore.hpp"
#include "player_engine.hpp"

using qn::LandingQuality;
using qn::PlayerEngine;
using qn::PlayerState;
using qn::PlayerStatus;
using qn::StepOutcome;

namespace {

const char* state_name(PlayerState s) {
    switch (s) {
        case PlayerState::Empty: return "EMPTY";
        case PlayerState::Ready: return "READY";
        case PlayerState::Playing: return "PLAYING";
        case PlayerState::Paused: return "PAUSED";
        case PlayerState::Ended: return "ENDED";
        case PlayerState::Error: return "ERROR";
    }
    return "?";
}

const char* quality_name(LandingQuality q) {
    return q == LandingQuality::Confirmed ? "CONFIRMED" : "ESTIMATED";
}

[[noreturn]] void fail(const std::string& msg) {
    std::fprintf(stderr, "trace_runner: %s\n", msg.c_str());
    std::exit(2);
}

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::size_t i = 0;
    while (i < line.size()) {
        while (i < line.size() && (line[i] == ' ' || line[i] == '\t')) ++i;
        std::size_t j = i;
        while (j < line.size() && line[j] != ' ' && line[j] != '\t') ++j;
        if (j > i) out.push_back(line.substr(i, j - i));
        i = j;
    }
    return out;
}

std::int64_t to_i64(const std::string& s) { return std::strtoll(s.c_str(), nullptr, 10); }

// Per-segment content-continuity bookkeeping (check_segments mirror).
struct SegmentTruth {
    std::int64_t anchor = -1;     // unset
    std::int64_t next_index = 0;  // frames already verified
    std::size_t checked = 0;      // log floats already verified
};

struct Runner {
    qn::EngineConfig cfg;
    std::uint64_t period = 0;
    std::map<int, qn::fake::SongConfig> songs;
    std::map<int, std::uint64_t> song_work_steps;
    std::optional<PlayerEngine> engine;

    std::uint64_t total_requested = 0, total_tick_media = 0, total_tick_silence = 0;
    std::map<std::uint64_t, SegmentTruth> truth;
    bool pending_eof_fold = false;
    int last_song_id = -1;

    PlayerEngine& eng() { return *engine; }

    void run();
    void exec_op(std::uint64_t idx, const std::vector<std::string>& t);
    void emit_snapshot(std::uint64_t idx, const char* op, const char* outcome);
    void check_invariants(std::uint64_t idx, const char* ctx);
    void check_content_continuity(std::uint64_t idx, const char* ctx);
};

void Runner::run() {
    std::vector<char> buf(1 << 16);
    std::uint64_t idx = 0;
    while (std::fgets(buf.data(), static_cast<int>(buf.size()), stdin)) {
        std::string line(buf.data());
        while (!line.empty() && (line.back() == '\n' || line.back() == '\r')) line.pop_back();
        if (line.empty() || line[0] == '#') continue;
        std::vector<std::string> t = split(line);
        if (t[0] == "TRACE") continue;
        if (t[0] == "CFG") {
            cfg.capacity_frames = static_cast<std::uint64_t>(to_i64(t[1]));
            cfg.read_chunk_frames = static_cast<std::uint64_t>(to_i64(t[2]));
            cfg.max_submit_frames = static_cast<std::uint64_t>(to_i64(t[3]));
            period = static_cast<std::uint64_t>(to_i64(t[4]));
            engine.emplace(cfg);
            continue;
        }
        if (t[0] == "SONG") {
            const int id = static_cast<int>(to_i64(t[1]));
            qn::fake::SongConfig c;
            c.total_frames = to_i64(t[2]);
            c.sample_rate = static_cast<std::int32_t>(to_i64(t[3]));
            c.channels = static_cast<std::int32_t>(to_i64(t[4]));
            c.seek_landing_offset = to_i64(t[6]);
            c.fail_at_frame = to_i64(t[7]);
            c.open_fails = t[8] == "1";
            c.seek_status = static_cast<std::int32_t>(to_i64(t[9]));
            c.seek_landing_unknown = t[10] == "1";
            c.unknown_duration = t[11] == "1";
            c.reopen_fails = t[12] == "1";
            if (c.channels != 2) {
                // Content-continuity decoding assumes the tag in the L slot.
                fail("trace songs must be stereo");
            }
            songs[id] = c;
            song_work_steps[id] = static_cast<std::uint64_t>(to_i64(t[5]));
            continue;
        }
        if (t[0] == "OP") {
            if (!engine) fail("CFG must precede OPs");
            exec_op(idx++, std::vector<std::string>(t.begin() + 1, t.end()));
            continue;
        }
        fail("unknown trace line: " + line);
    }
}

void Runner::exec_op(std::uint64_t idx, const std::vector<std::string>& t) {
    const std::string& op = t[0];
    if (op == "open") {
        const int id = static_cast<int>(to_i64(t[1]));
        const auto it = songs.find(id);
        if (it == songs.end()) fail("open: unknown song id");
        it->second.live.reset();  // fresh handle: fresh counters
        last_song_id = id;
        song_io io{};
        io.userdata = &it->second;
        io.read = [](void*, std::uint8_t*, std::size_t) -> std::int64_t { return 0; };
        io.seek = [](void*, std::int64_t) -> std::int64_t { return 0; };
        io.size = [](void*) -> std::int64_t { return 0; };
        const PlayerStatus st = eng().open(io);
        // work_steps is the fake's in-flight latency knob (oracle coupling).
        if (st == PlayerStatus::Ok) eng().debug_set_work_steps(song_work_steps[id]);
        emit_snapshot(idx, "open",
                      st == PlayerStatus::Ok         ? "ok"
                      : st == PlayerStatus::ErrOpenFailed ? "openfail"
                                                          : "illegal");
        return;
    }
    if (op == "play") {
        const PlayerStatus st = eng().play();
        emit_snapshot(idx, "play",
                      st == PlayerStatus::Ok            ? "ok"
                      : st == PlayerStatus::ErrSeekFailed ? "seekfail"  // restart
                                                          : "illegal");
        return;
    }
    if (op == "pause") {
        eng().pause();
        emit_snapshot(idx, "pause", "ok");
        return;
    }
    if (op == "stop") {
        // Reopen failure inside stop() recovery is not an op failure: the
        // op completes with ERROR state + last_error in the snapshot.
        eng().stop();
        emit_snapshot(idx, "stop", "ok");
        return;
    }
    if (op == "seek") {
        const std::int64_t us = to_i64(t[1]);
        std::int64_t landing = 0;
        const PlayerStatus st = eng().seek(us, &landing);
        emit_snapshot(idx, "seek",
                      st == PlayerStatus::Ok          ? "ok"
                      : st == PlayerStatus::ErrSeekFailed ? "seekfail"
                                                          : "illegal");
        return;
    }
    if (op == "decode") {
        const std::uint64_t n = static_cast<std::uint64_t>(to_i64(t[1]));
        for (std::uint64_t i = 0; i < n; ++i) {
            const auto it = songs.find(last_song_id);
            if (it != songs.end() && it->second.live) {
                const std::int64_t rem =
                    it->second.total_frames - it->second.live->position;
                eng().debug_set_source_hint(rem >= 0 ? rem : 0);
            }
            const qn::StepReport rep = eng().worker_step();
            if (rep.outcome == StepOutcome::Begin) {
                // Did this read exhaust the fake? Then the EOF confirmation
                // folds into this chunk's publication op.
                if (it != songs.end() && it->second.live &&
                    it->second.live->position >= it->second.total_frames) {
                    pending_eof_fold = true;
                }
            } else if (rep.outcome == StepOutcome::Wrote) {
                if (pending_eof_fold) {
                    eng().debug_set_source_hint(0);
                    eng().worker_step();  // SONG_EOF confirmation read
                    pending_eof_fold = false;
                }
            } else if (rep.outcome == StepOutcome::Stale) {
                pending_eof_fold = false;
            }
        }
        emit_snapshot(idx, "decode", "ok");
        return;
    }
    if (op == "submit") {
        const std::uint64_t n = static_cast<std::uint64_t>(to_i64(t[1]));
        for (std::uint64_t i = 0; i < n; ++i) {
            const qn::SubmitReport rep = eng().submit(period);
            if (std::strcmp(rep.kind, "idle") != 0) {
                total_requested += period;
                total_tick_media += rep.media_frames;
                total_tick_silence += rep.silence_frames;
                if (rep.media_frames + rep.silence_frames != period) {
                    fail("tick accounting: submitted != requested");
                }
            }
        }
        emit_snapshot(idx, "submit", "ok");
        return;
    }
    if (op == "render") {
        const std::uint64_t k = static_cast<std::uint64_t>(to_i64(t[1]));
        const std::int64_t gen_back = to_i64(t[2]);
        const std::int64_t gen =
            gen_back > 0
                ? static_cast<std::int64_t>(eng().snapshot().epoch) - gen_back
                : qn::PlayerEngine::kCurrentGeneration;
        eng().backend_render(static_cast<std::int64_t>(k * period), gen);
        emit_snapshot(idx, "render", "ok");
        return;
    }
    fail("unknown op: " + op);
}

void Runner::emit_snapshot(std::uint64_t idx, const char* op, const char* outcome) {
    const qn::EngineSnapshot s = eng().snapshot();
    const auto it = songs.find(last_song_id);
    const std::int64_t fake_pos =
        (it != songs.end() && it->second.live) ? it->second.live->position : -1;

    std::string err(s.last_error);
    for (char& c : err) {
        if (c == ' ' || c == ',') c = '_';
    }
    std::printf(
        "SNAP %llu %s %s %s %lld %s %lld %lld %lld %d %llu %llu %llu %llu %d "
        "%llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu "
        "%llu %llu %llu %llu %s\n",
        static_cast<unsigned long long>(idx), op, outcome, state_name(s.state),
        static_cast<long long>(s.media_position_frames), quality_name(s.position_quality),
        static_cast<long long>(s.decoded_source_position),
        static_cast<long long>(fake_pos), static_cast<long long>(s.duration_frames),
        s.duration_known ? 1 : 0,
        static_cast<unsigned long long>(s.queued_media_frames),
        static_cast<unsigned long long>(s.capacity_frames),
        static_cast<unsigned long long>(s.epoch),
        static_cast<unsigned long long>(s.segment), s.source_eof ? 1 : 0,
        static_cast<unsigned long long>(s.underrun_count),
        static_cast<unsigned long long>(s.underrun_silence_output_frames),
        static_cast<unsigned long long>(s.preroll_events),
        static_cast<unsigned long long>(s.preroll_silence_output_frames),
        static_cast<unsigned long long>(s.eos_silence_output_frames),
        static_cast<unsigned long long>(s.decoded_source_frames),
        static_cast<unsigned long long>(s.submitted_output_frames),
        static_cast<unsigned long long>(s.rendered_output_frames),
        static_cast<unsigned long long>(s.pending_output_frames),
        static_cast<unsigned long long>(s.discarded_output_frames),
        static_cast<unsigned long long>(s.submitted_media_frames),
        static_cast<unsigned long long>(s.rendered_media_frames),
        static_cast<unsigned long long>(s.rendered_gap_output_frames),
        static_cast<unsigned long long>(s.pending_media_frames),
        static_cast<unsigned long long>(s.discarded_output_media_frames),
        static_cast<unsigned long long>(s.discarded_stale_media_frames),
        static_cast<unsigned long long>(s.stale_render_events), err.c_str());
    std::fflush(stdout);
    check_invariants(idx, op);
}

void Runner::check_invariants(std::uint64_t idx, const char* ctx) {
    char why[256];
    const qn::EngineSnapshot s = eng().snapshot();
    const auto& ring = eng().ring_debug();
    if (!ring.check_invariants(why, sizeof why)) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: ring: %s\n",
                     static_cast<unsigned long long>(idx), ctx, why);
        std::exit(3);
    }
    const std::uint64_t inflight = eng().in_flight_frames();
    if (s.decoded_source_frames !=
        ring.produced_total() + s.discarded_stale_media_frames + inflight) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: decode conservation\n",
                     static_cast<unsigned long long>(idx), ctx);
        std::exit(3);
    }
    if (s.submitted_output_frames !=
        s.pending_output_frames + s.rendered_output_frames + s.discarded_output_frames) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: output conservation\n",
                     static_cast<unsigned long long>(idx), ctx);
        std::exit(3);
    }
    if (s.submitted_media_frames !=
        s.pending_media_frames + s.rendered_media_frames + s.discarded_output_media_frames) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: media conservation\n",
                     static_cast<unsigned long long>(idx), ctx);
        std::exit(3);
    }
    if (s.rendered_output_frames != s.rendered_media_frames + s.rendered_gap_output_frames) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: rendered output split\n",
                     static_cast<unsigned long long>(idx), ctx);
        std::exit(3);
    }
    if (total_requested != total_tick_media + total_tick_silence) {
        std::fprintf(stderr, "INVARIANT-FAIL op=%llu %s: tick accounting\n",
                     static_cast<unsigned long long>(idx), ctx);
        std::exit(3);
    }
    if (s.state != PlayerState::Empty) {
        if (s.state == PlayerState::Ended && s.duration_known) {
            if (s.media_position_frames != s.duration_frames) {
                std::fprintf(stderr,
                             "INVARIANT-FAIL op=%llu %s: ENDED position != duration\n",
                             static_cast<unsigned long long>(idx), ctx);
                std::exit(3);
            }
        } else {
            const std::int64_t base = eng().segment_anchor(s.segment);
            const std::int64_t seg_rendered = eng().segment_rendered_media();
            if (s.media_position_frames != base + seg_rendered) {
                std::fprintf(stderr,
                             "INVARIANT-FAIL op=%llu %s: clock continuity: pos=%lld "
                             "!= base %lld + rendered %lld\n",
                             static_cast<unsigned long long>(idx), ctx,
                             static_cast<long long>(s.media_position_frames),
                             static_cast<long long>(base),
                             static_cast<long long>(seg_rendered));
                std::exit(3);
            }
        }
        if (s.duration_known) {
            if (s.media_position_frames < 0 || s.media_position_frames > s.duration_frames) {
                std::fprintf(stderr,
                             "INVARIANT-FAIL op=%llu %s: position outside song\n",
                             static_cast<unsigned long long>(idx), ctx);
                std::exit(3);
            }
        } else if (s.duration_frames != -1) {
            std::fprintf(stderr,
                         "INVARIANT-FAIL op=%llu %s: unknown duration must stay -1\n",
                         static_cast<unsigned long long>(idx), ctx);
            std::exit(3);
        }
    }
    check_content_continuity(idx, ctx);
}

void Runner::check_content_continuity(std::uint64_t idx, const char* ctx) {
    const auto& log = eng().backend().rendered_log();
    for (const auto& entry : log) {
        SegmentTruth& tr = truth[entry.segment];
        if (tr.checked >= entry.pcm.size()) continue;
        if (tr.anchor < 0 && !entry.pcm.empty()) {
            if (eng().segment_landing_quality(entry.segment) == LandingQuality::Confirmed) {
                tr.anchor = eng().segment_anchor(entry.segment);
            } else {
                // Hidden truth only; never a production input.
                tr.anchor = static_cast<std::int64_t>(llroundf(entry.pcm[0] - 0.25f));
            }
        }
        // Traces are stereo; the tag lives in the L slot.
        for (std::size_t i = tr.checked; i + 1 < entry.pcm.size(); i += 2) {
            const std::int64_t tag = static_cast<std::int64_t>(llroundf(entry.pcm[i] - 0.25f));
            const std::int64_t expect = tr.anchor + tr.next_index;
            if (tag != expect) {
                std::fprintf(stderr,
                             "INVARIANT-FAIL op=%llu %s: content continuity: segment "
                             "%llu index %lld tag %lld expected %lld\n",
                             static_cast<unsigned long long>(idx), ctx,
                             static_cast<unsigned long long>(entry.segment),
                             static_cast<long long>(tr.next_index),
                             static_cast<long long>(tag),
                             static_cast<long long>(expect));
                std::exit(3);
            }
            ++tr.next_index;
        }
        tr.checked = entry.pcm.size();
    }
}

}  // namespace

int main() {
    Runner r;
    r.run();
    return 0;
}
