#!/usr/bin/env python3
"""E09 correctness gate — E08's 44-case corpus replayed across the runtime ladder.

Gate policy (executable, not post-hoc):

  exact-required + tolerance-allowed = accepted

  - exact-required: status, container, codec, sample_rate/channels, duration,
    metadata, artwork sha, decode status/samples/frames/canonical_len, eof,
    seek targets/resume points/status, and for integer/lossless families the
    full PCM hashes. These must match the native twin exactly.
  - tolerance-allowed: ONLY the PCM-derived hash fields
    (decode.canonical_f32_sha256, suffix[*] hashes, seek suffix_sha256) of
    explicitly listed float-DSP codegen-sensitive families (mp3, aac), and
    only when:
        a) every structural field still matches the native twin exactly;
        b) the case's fixture has per-fixture PCM evidence in tolerance.json
           (generated by tools/wasm_tolerance_study.py) with equal
           sample/frame counts and max_abs_delta <= TOLERANCE_BOUND.

Every case is classified exactly one of: exact_matches / accepted_with_
tolerance / rejected. A runtime PASS requires rejected == 0. The 28/44
exact + 16/44 accepted-with-tolerance fact is kept visible — never hidden.

Degraded (typed) cases must fail the same way as the reference (no crash,
no hang, valid JSON); exit codes 0/1 with parseable JSON are acceptable.

The Emscripten/V8 row runs in a separate Node harness (tools/wasm_gate_em.py
-> correctness-em.json) because the em session overwrites the shared WASI
guest artifacts; wasm_summary.py joins the two authorities.

Artifact selection (pristine vs WAMR-workaround, see E09-WAMR-1):
  - native/wasm3/wasmtime consume the PRISTINE guest;
  - wamr classic-interp consumes the deterministic workaround copy;
  - wamr_aot consumes the wamrc .aot compiled from the pristine guest.

Results land in bench/results/wasm/correctness.json.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "corpus" / "fixtures"
OUT = ROOT / "bench" / "results" / "wasm" / "correctness.json"
TOL = ROOT / "bench" / "results" / "wasm" / "tolerance.json"
# classic-interp engines need real wall time on long fixtures (mp3-long
# correct ≈ 4 near-full decode passes ≈ 2 min CPU under WAMR interp; perf
# shows 99.4% wasm_interp_call_func_bytecode — cost, not a hang)
TIMEOUT_S = 600

WASM_ART = ROOT / "build" / "artifacts" / "wasm"

RUNTIMES = [
    ("native", ROOT / "build/artifacts/qn_native_runner", None),
    ("wamr", ROOT / "build/artifacts/qn_wamr_runner",
     WASM_ART / "qn_guest_bench.wamr-workaround.wasm"),
    ("wamr_aot", ROOT / "build/artifacts/qn_wamr_aot_runner",
     WASM_ART / "qn_guest_bench.aot"),
    ("wasm3", ROOT / "build/artifacts/qn_wasm3_runner",
     WASM_ART / "qn_guest_bench.wasm"),
    ("wasmtime", ROOT / "build/artifacts/qn_wasmtime_runner",
     WASM_ART / "qn_guest_bench.wasm"),
]

# Float-DSP codegen-sensitive families whose PCM hashes may be tolerated;
# every other family is exact-required on the full observable.
TOLERATED_FAMILIES = {"mp3", "aac"}
# per-fixture evidence bound (max |delta| between native and wasm canonical
# f32 PCM); entries above this bound fail the tolerance policy.
TOLERANCE_BOUND = 1e-6


def load_cases():
    cases = {}
    for mf in ("stage-a.json", "common-formats.json"):
        d = json.loads((ROOT / "corpus" / "manifest" / mf).read_text())
        for c in d["cases"]:
            cases[c["id"]] = c
    return cases


def run_correct(binary, wasm, fixture):
    if wasm is None:  # native twin: own CLI (<file> correct)
        cmd = [str(binary), str(fixture), "correct"]
    else:
        cmd = [str(binary), str(wasm), "correct", str(fixture)]
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=TIMEOUT_S)
    except subprocess.TimeoutExpired:
        return {"_gate": "timeout"}
    lines = [l for l in p.stdout.splitlines() if l.startswith("{")]
    if not lines:
        return {"_gate": "no-json", "_stderr": p.stderr[-200:]}
    try:
        out = json.loads(lines[-1])
    except json.JSONDecodeError:
        return {"_gate": "bad-json"}
    if p.returncode not in (0, 1):
        return {"_gate": f"exit-{p.returncode}", "_observed": out}
    out["_gate"] = "json"
    return out


def observable(j):
    """The fields the gate compares across runtimes (wall-clock stripped:
    decode_ms/seek_ms are timing, not observable behavior — E09-gate-1)."""
    if j.get("_gate") != "json":
        return {"gate": j.get("_gate")}
    if j.get("status") != "ok":
        return {"status": j.get("status"),
                "error": j.get("error", j.get("first_error", ""))}
    seeks = [(s.get("target_us"), s.get("resume_sample"), s.get("status"),
              s.get("suffix_sha256")) for s in j.get("seeks", [])]
    art = j.get("artwork") or {}
    dec = j.get("decode") or {}
    # AV_NOPTS_VALUE (INT64_MIN) means "unknown duration"; the exact sentinel
    # does not survive Node's JSON.parse (rounds to -9223372036854776000),
    # so the observable normalizes negative durations to None. Real audio
    # durations are always positive; only the unknown sentinel is negative.
    dur = j.get("duration_us")
    dur = None if dur is None or dur < 0 else dur
    return {
        "status": "ok",
        "container": j.get("container"),
        "codec": j.get("codec"),
        "sample_rate": j.get("sample_rate"),
        "channels": j.get("channels"),
        "duration_us": dur,
        "metadata": j.get("metadata"),
        "artwork_sha": art.get("sha256"),
        "decode": {k: dec.get(k) for k in
                   ("status", "samples", "frames",
                    "canonical_f32_sha256", "canonical_len")},
        "eof": j.get("eof"),
        "suffix": j.get("suffix"),
        "seeks": seeks,
    }


def codec_family(case):
    return (case.get("expect") or {}).get("codec") or ""


def structural_observable(o):
    """The tolerance-invariant projection: identical to `observable` except
    the PCM-derived hash fields are dropped (they may legitimately differ
    for float-DSP families; everything else must match exactly)."""
    if o.get("status") != "ok" or "decode" not in o:
        return o
    out = dict(o)
    dec = dict(out["decode"])
    dec.pop("canonical_f32_sha256", None)
    out["decode"] = dec
    out["suffix"] = [idx for idx, _ in (out.get("suffix") or [])]
    out["seeks"] = [(t, r, st) for t, r, st, _ in (out.get("seeks") or [])]
    return out


def load_tolerance():
    if not TOL.exists():
        return {}
    return json.loads(TOL.read_text()).get("fixtures", {})


def classify(case, want, obs, tol):
    """Return ("exact" | "tolerated" | "rejected", reason)."""
    if obs == want:
        return "exact", None
    fam = codec_family(case)
    if fam not in TOLERATED_FAMILIES:
        return "rejected", (f"structural/codec mismatch outside tolerated "
                            f"families ({fam or 'unknown'})")
    if structural_observable(obs) != structural_observable(want):
        return ("rejected",
                "structural fields differ (tolerance only covers PCM-hash fields)")
    ev = tol.get(case["file"])
    if not ev:
        return "rejected", f"no per-fixture tolerance evidence for {case['file']}"
    if ev.get("samples") != want["decode"].get("samples") or \
            ev.get("frames") != want["decode"].get("frames"):
        return "rejected", f"tolerance evidence sample/frame counts mismatch"
    if ev.get("max_abs_delta") is None or ev["max_abs_delta"] > TOLERANCE_BOUND:
        return "rejected", (f"tolerance evidence max_abs_delta="
                            f"{ev.get('max_abs_delta')} exceeds bound "
                            f"{TOLERANCE_BOUND}")
    return "tolerated", None


def diff_fields(want, obs):
    return {k: (want.get(k), obs.get(k))
            for k in set(want) | set(obs) if want.get(k) != obs.get(k)}


def main():
    cases = load_cases()
    tol = load_tolerance()
    # --reclassify: recompute the summary from the committed raw per-case
    # guest JSON with the CURRENT observable+tolerance policy, without
    # re-running the runners (used when only the policy/observable changed —
    # the raw measurements are unchanged).
    if "--reclassify" in sys.argv and OUT.exists():
        committed = json.loads(OUT.read_text())
        results = committed.get("raw", {})
    else:
        # targeted reruns: --runtime wamr_aot reruns a single row (the other
        # rows are preserved from the committed correctness.json)
        only = None
        if "--runtime" in sys.argv:
            only = sys.argv[sys.argv.index("--runtime") + 1]
        results = {}
        if only is not None:
            committed = OUT.read_text() if OUT.exists() else "{}"
            try:
                results = json.loads(committed).get("raw", {})
            except json.JSONDecodeError:
                results = {}
        for rt, binary, guest in RUNTIMES:
            if only is not None and rt != only:
                continue
            if not binary.exists():
                results[rt] = {"_gate": "runner-missing"}
                continue
            per = {}
            for cid, c in cases.items():
                fx = FIXTURES / c["file"]
                per[cid] = run_correct(binary, guest, fx)
            results[rt] = per

    ref = {cid: observable(j) for cid, j in results["native"].items()}
    summary = {}
    for rt, per in results.items():
        if isinstance(per, dict) and per.get("_gate"):
            summary[rt] = per["_gate"]
            continue
        exact = accepted = rejected = 0
        fails, tol_ok = [], []
        for cid, c in cases.items():
            obs = observable(per[cid])
            want = ref[cid]
            kind, reason = classify(c, want, obs, tol)
            if kind == "exact":
                exact += 1
            elif kind == "tolerated":
                accepted += 1
                tol_ok.append(cid)
            else:
                rejected += 1
                fails.append({"case": cid, "reason": reason,
                              "delta": diff_fields(want, obs)})
        summary[rt] = {"exact_matches": exact,
                       "accepted_with_tolerance": accepted,
                       "rejected": rejected,
                       "total": len(cases),
                       "tolerance_accepted_cases": tol_ok,
                       "failures": fails}

    out = {"corpus": "stage-a-v1 + common-formats-v1 (44 cases)",
           "reference": "native twin",
           "policy": {
               "exact_required": "all observable fields except the PCM-derived "
                                 "hash fields listed below",
               "tolerance_allowed": {
                   "families": sorted(TOLERATED_FAMILIES),
                   "pcm_hash_fields": ["decode.canonical_f32_sha256",
                                       "suffix[*].hash", "seeks[*].suffix_sha256"],
                   "per_fixture_evidence": "tolerance.json (max_abs_delta "
                                           f"<= {TOLERANCE_BOUND}, equal "
                                           "sample/frame counts)",
               },
               "accepted": "exact_matches + accepted_with_tolerance",
           },
           "summary": summary, "raw": results}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=1, ensure_ascii=False))
    ok = True
    for rt, s in summary.items():
        if isinstance(s, dict):
            line = (f"{rt}: exact={s['exact_matches']} "
                    f"accepted_with_tolerance={s['accepted_with_tolerance']} "
                    f"rejected={s['rejected']}")
            print(line)
            for f in s["failures"][:5]:
                print(f"  REJECT {f['case']}: {f['reason']}")
            if s["rejected"]:
                ok = False
        else:
            print(f"{rt}: {s}")
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
